version: '3.8'

services:
  auth_db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib

  auth_cache:
    image: redis:latest
    container_name: auth_cache
    ports:
      - "6379:6379"
    volumes:
      - auth_cache_data:/data

volumes:
  auth_db_data:
  auth_cache_data: